package gui;

import capturer.ImageReader;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileFilter;
import org.jvnet.substance.SubstanceLegacyDefaultLookAndFeel;
import org.jvnet.substance.skin.SubstanceBusinessBlackSteelLookAndFeel;
import org.jvnet.substance.skin.SubstanceChallengerDeepLookAndFeel;
import org.jvnet.substance.skin.SubstanceEmeraldDuskLookAndFeel;
import org.jvnet.substance.skin.SubstanceMagmaLookAndFeel;
import org.jvnet.substance.skin.SubstanceOfficeBlue2007LookAndFeel;
import org.jvnet.substance.skin.SubstanceOfficeSilver2007LookAndFeel;
import org.jvnet.substance.skin.SubstanceRavenGraphiteGlassLookAndFeel;
import org.jvnet.substance.skin.SubstanceRavenLookAndFeel;
import sound.Sound;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on 20/01/2010, 21:25:09
 */
/**
 *
 * @author Rodrigo
 */
public class MainFrame extends javax.swing.JFrame {

    private boolean capturando;
    private int nChannels;

    /** Creates new form MainFrame */
    public MainFrame() {

        initComponents();
        jComboBoxTaxa.setSelectedIndex(2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSensibilidade = new javax.swing.JLabel();
        jSliderSensibilidade = new javax.swing.JSlider();
        jButtonRestaurar = new javax.swing.JButton();
        jComboBoxSom = new javax.swing.JComboBox();
        jLabelTipo = new javax.swing.JLabel();
        jLabelTaxa = new javax.swing.JLabel();
        jLabelFalantes = new javax.swing.JLabel();
        jTextFieldSom = new javax.swing.JTextField();
        jButtonAbrir = new javax.swing.JButton();
        jLabelSom = new javax.swing.JLabel();
        jComboBoxTaxa = new javax.swing.JComboBox();
        jComboBoxAltoFalantes = new javax.swing.JComboBox();
        jButtonCapturar = new javax.swing.JButton();
        jLabelTema = new javax.swing.JLabel();
        jComboBoxTema = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LightSound");

        jLabelSensibilidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelSensibilidade.setText("Sensibilidade:");

        jSliderSensibilidade.setFont(new java.awt.Font("Tahoma", 0, 12));
        jSliderSensibilidade.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderSensibilidadeStateChanged(evt);
            }
        });

        jButtonRestaurar.setFont(new java.awt.Font("Tahoma", 0, 12));
        jButtonRestaurar.setText("Restaurar");
        jButtonRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestaurarActionPerformed(evt);
            }
        });

        jComboBoxSom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxSom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Volume", "Velocidade" }));
        jComboBoxSom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSomActionPerformed(evt);
            }
        });

        jLabelTipo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelTipo.setText("Tipo De Alteração Do Som:");

        jLabelTaxa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelTaxa.setText("Taxa De Captura:");

        jLabelFalantes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelFalantes.setText("Número De Alto Falantes:");

        jTextFieldSom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldSom.setText("C:\\Users\\Rodrigo\\Documents\\Wavs\\hino8bitsmono44khz.wav");

        jButtonAbrir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonAbrir.setText("Abrir");
        jButtonAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirActionPerformed(evt);
            }
        });

        jLabelSom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelSom.setText("Som:");

        jComboBoxTaxa.setFont(new java.awt.Font("Tahoma", 0, 12));
        jComboBoxTaxa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1 quadro por segundo", "2 quadros por segundo", "3 quadros por segundo", "4 quadros por segundo", "5 quadros por segundo", "6 quadros por segundo" }));
        jComboBoxTaxa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTaxaActionPerformed(evt);
            }
        });

        jComboBoxAltoFalantes.setFont(new java.awt.Font("Tahoma", 0, 12));
        jComboBoxAltoFalantes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "4", "6" }));
        jComboBoxAltoFalantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAltoFalantesActionPerformed(evt);
            }
        });

        jButtonCapturar.setFont(new java.awt.Font("Tahoma", 1, 16));
        jButtonCapturar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rodrigo\\Documents\\NetBeansProjects\\LightSound\\play.png")); // NOI18N
        jButtonCapturar.setText("Iniciar Captura");
        jButtonCapturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCapturarActionPerformed(evt);
            }
        });

        jLabelTema.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelTema.setText("Tema:");

        jComboBoxTema.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Emerald Dusk", "Challenger Deep", "Magma", "Business Black Steel", "Office Blue 2007", "Office Silver 2007", "Raven", "Raven Graphite Glass", "Legacy" }));
        jComboBoxTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTemaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFalantes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxAltoFalantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxSom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonCapturar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelSom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSom, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAbrir, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelSensibilidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderSensibilidade, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRestaurar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTaxa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxTaxa, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabelTema)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxTema, 0, 133, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonAbrir, jButtonRestaurar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jSliderSensibilidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRestaurar)
                    .addComponent(jLabelSensibilidade))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSom))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelFalantes)
                    .addComponent(jComboBoxAltoFalantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTipo)
                    .addComponent(jComboBoxSom, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelTaxa)
                    .addComponent(jComboBoxTaxa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTema)
                    .addComponent(jComboBoxTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonCapturar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonAbrir, jButtonRestaurar, jSliderSensibilidade, jTextFieldSom});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private class WaveFilter extends FileFilter {

        @Override
        public boolean accept(File f) {
            return f.isDirectory() || f.getName().endsWith(".wav");
        }

        @Override
        public String getDescription() {
            return "*.wav";
        }
    }

    private void jButtonAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new WaveFilter());
        int option = chooser.showOpenDialog(null);

        if (option == JFileChooser.APPROVE_OPTION) {
            System.out.println("Seleciona arquivo");
            String fileName = chooser.getSelectedFile().getAbsolutePath();
            jTextFieldSom.setText(fileName);
        }
}//GEN-LAST:event_jButtonAbrirActionPerformed

    private void jButtonCapturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCapturarActionPerformed
        jSliderSensibilidade.setEnabled(capturando);
        jButtonRestaurar.setEnabled(capturando);
        jTextFieldSom.setEnabled(capturando);
        jButtonAbrir.setEnabled(capturando);
        jComboBoxTema.setEnabled(capturando);
        jComboBoxAltoFalantes.setEnabled(capturando);
        jComboBoxSom.setEnabled(capturando);
        jComboBoxTaxa.setEnabled(capturando);
        jLabelSensibilidade.setEnabled(capturando);
        jLabelSom.setEnabled(capturando);
        jLabelFalantes.setEnabled(capturando);
        jLabelTaxa.setEnabled(capturando);
        jLabelTema.setEnabled(capturando);
        jLabelTipo.setEnabled(capturando);
        if (capturando) {
            jButtonCapturar.setIcon(new ImageIcon("play.png"));
            jButtonCapturar.setText(" Iniciar Captura");
            pararCaptura();
        } else {
            jButtonCapturar.setIcon(new ImageIcon("stop.png"));
            jButtonCapturar.setText(" Parar Captura");
            iniciarCaptura();
        }
}//GEN-LAST:event_jButtonCapturarActionPerformed

    private void jButtonRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestaurarActionPerformed
        jSliderSensibilidade.setValue(50);
}//GEN-LAST:event_jButtonRestaurarActionPerformed

    private void jSliderSensibilidadeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderSensibilidadeStateChanged
        if (capturando) {
            iniciarCaptura();
        }
}//GEN-LAST:event_jSliderSensibilidadeStateChanged

    private void jComboBoxAltoFalantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAltoFalantesActionPerformed
        if (capturando) {
            iniciarCaptura();
        }
    }//GEN-LAST:event_jComboBoxAltoFalantesActionPerformed

    private void jComboBoxSomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSomActionPerformed
        if (capturando) {
            iniciarCaptura();
        }
    }//GEN-LAST:event_jComboBoxSomActionPerformed

    private void jComboBoxTaxaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTaxaActionPerformed
        if (capturando) {
            iniciarCaptura();
        }
    }//GEN-LAST:event_jComboBoxTaxaActionPerformed

    private void jComboBoxTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTemaActionPerformed
        try {
            switch (jComboBoxTema.getSelectedIndex()) {
                case 0:
                    UIManager.setLookAndFeel(new SubstanceEmeraldDuskLookAndFeel());
                    break;
                case 1:
                    UIManager.setLookAndFeel(new SubstanceChallengerDeepLookAndFeel());
                    break;
                case 2:
                    UIManager.setLookAndFeel(new SubstanceMagmaLookAndFeel());
                    break;
                case 3:
                    UIManager.setLookAndFeel(new SubstanceBusinessBlackSteelLookAndFeel());
                    break;
                case 4:
                    UIManager.setLookAndFeel(new SubstanceOfficeBlue2007LookAndFeel());
                    break;
                case 5:
                    UIManager.setLookAndFeel(new SubstanceOfficeSilver2007LookAndFeel());
                    break;
                case 6:
                    UIManager.setLookAndFeel(new SubstanceRavenLookAndFeel());
                    break;
                case 7:
                    UIManager.setLookAndFeel(new SubstanceRavenGraphiteGlassLookAndFeel());
                    break;
                case 8:
                    UIManager.setLookAndFeel(new SubstanceLegacyDefaultLookAndFeel());
                    break;
            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }

}//GEN-LAST:event_jComboBoxTemaActionPerformed

    private int getNChannels() {
        switch (jComboBoxAltoFalantes.getSelectedIndex()) {
            case 1:
                return nChannels = 4;
            case 2:
                return nChannels = 6;
            default:
                return nChannels = 2;
        }
    }

    private int getSensibility() {
        Integer value = jSliderSensibilidade.getValue();
        return 200 - value;
    }

    private int getRatio() {
        switch (jComboBoxTaxa.getSelectedIndex()) {
            case 0:
                return 30;
            case 1:
                return 15;
            case 3:
                return 8;
            case 4:
                return 6;
            case 5:
                return 4;
            default:
                return 11;
        }
    }

    public void iniciarCaptura() {
        pararCaptura();
        capturando = true;
        System.out.println("Iniciando captura");
        String fileName = jTextFieldSom.getText();
        if (fileName.equals("")) {
            JOptionPane.showMessageDialog(null, "Escolha uma musica primeiro", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            new LoopThread(fileName).start();
        }
    }

    private float[] getPercents(boolean[][] matriz, boolean[][] atual) {
        float[] result = new float[nChannels];
        int nTotal = (atual.length * atual[0].length) / nChannels;
        int diffR = 0, diffL = 0;

        int meio = atual.length / 2;
        //para 2 canais

        for (int i = 0; i < meio; i++) {
            for (int j = 0; j < atual[0].length; j++) {
                if (atual[i][j] != matriz[i][j]) {
                    diffL++;
                }
                if (atual[i+meio][j] != matriz[i+meio][j]) {
                    diffR++;
                }
            }
        }
        result[0] = ((float) diffL) / nTotal;
        result[1] = ((float) diffR) / nTotal;

        System.out.println("DiffL " + diffL + ", DiffR " + diffR + ", Total " + nTotal);
        return result;
    }

    public void pararCaptura() {
        capturando = false;
        System.out.println("Parando captura");
        
    }

    private class LoopThread extends Thread {

        private String fileName;

        public LoopThread(String fileName) {
            this.fileName = fileName;
        }

        @Override
        public void run() {
            try {
                Sound sound = new Sound(fileName, getNChannels());
                ImageReader imageReader = new ImageReader(new String[]{"dshow://"}, getSensibility(), getRatio());

                boolean[][] matriz = imageReader.getIluminedMatrix();

                System.out.println("Matriz " + matriz.length + " x " + matriz[0].length);

                while (capturando) {
                    boolean[][] matrizAux = imageReader.getIluminedMatrix();
                    float[] percents = getPercents(matriz, matrizAux);

                    //alterar volume
                    if (jComboBoxSom.getSelectedIndex() == 0) {
                        sound.setNewBalanceAndVolume(percents[0], percents[1]);
                    } //alterar velocidade
                    else {
                        sound.setNewSpeed(percents[0], percents[1]);
                    }
                    matriz = matrizAux;
                }
                ImageReader.stop();
                sound.stop();
            } catch (UnsupportedAudioFileException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }


        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    UIManager.setLookAndFeel(new SubstanceEmeraldDuskLookAndFeel());
                } catch (UnsupportedLookAndFeelException ex) {
                    ex.printStackTrace();
                }
                MainFrame frame = new MainFrame();
                frame.setVisible(true);
                frame.setLocationRelativeTo(null);
            }
        });
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbrir;
    private javax.swing.JButton jButtonCapturar;
    private javax.swing.JButton jButtonRestaurar;
    private javax.swing.JComboBox jComboBoxAltoFalantes;
    private javax.swing.JComboBox jComboBoxSom;
    private javax.swing.JComboBox jComboBoxTaxa;
    private javax.swing.JComboBox jComboBoxTema;
    private javax.swing.JLabel jLabelFalantes;
    private javax.swing.JLabel jLabelSensibilidade;
    private javax.swing.JLabel jLabelSom;
    private javax.swing.JLabel jLabelTaxa;
    private javax.swing.JLabel jLabelTema;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JSlider jSliderSensibilidade;
    private javax.swing.JTextField jTextFieldSom;
    // End of variables declaration//GEN-END:variables
}
